### ISSUE TITLE
调用 send_like (好友赞出错)

### ISSUE THREAD

**Issue by ctaoist** [cqmoe/python-aiocqhttp#13]
具体错误为：
```sh
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/none/command.py", line 521, in _real_run_command
    await asyncio.wait_for(future, timeout)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 339, in wait_for
    return (yield from fut)
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 126, in send
    return self.gen.send(value)
  File "/usr/lib/python3.6/site-packages/none/command.py", line 61, in run
    await self.func(session)
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/none-bot/plugins/likeme.py", line 13, in likeme
    await bot.send_like(user_id=session.ctx['user_id'], times=1)
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/usr/lib/python3.6/site-packages/aiocqhttp/api.py", line 170, in call_action
    action, **params)
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/usr/lib/python3.6/site-packages/aiocqhttp/api.py", line 140, in call_action
    return _handle_api_result(await ResultStore.fetch(seq))
  File "/usr/lib/python3.6/site-packages/aiocqhttp/api.py", line 39, in _handle_api_result
    raise ActionFailed(retcode=result.get('retcode'))
aiocqhttp.exceptions.ActionFailed
```
难道是 酷q那边的api有问题？？？

**Comment by stdrc** [comment]
@275761919 注意观察， aiocqhttp.exceptions 里面的异常，一般需要 except 一下，看一下异常的 retcode 属性是什么，然后参照文档查看是什么问题，不过你这个多半是因为 酷Q Air 不能发好友赞，可以看看 酷Q 的运行日志

**Comment by ctaoist** [comment]
@richardchien 
感谢提醒，确实是 air 不支持。
懂了，是 air 不配
