### ISSUE TITLE
aiocqhttp.exceptions.ApiNotAvailable

### ISSUE THREAD

**Issue by satouriko** [cqmoe/python-aiocqhttp#18]
同样的代码发送文本（小的消息）没事，发送图片（base64编码，较大）抛出 ApiNotAvailable 异常，怀疑跟 Websocket Fragmentation 有关 https://github.com/richardchien/coolq-http-api/issues/85

```
ujson module not found, using json
msgpack not installed, MsgPackSerializer unavailable
Task exception was never retrieved
future: <Task finished coro=<main_loop() done, defined at /nijigasaki-bot/nijigasaki/app/twitter.py:28> exception=ApiNotAvailable()>
Traceback (most recent call last):
  File "/nijigasaki-bot/nijigasaki/app/twitter.py", line 32, in main_loop
    await do_feed()
  File "/nijigasaki-bot/nijigasaki/app/twitter.py", line 59, in do_feed
    f"{tweet['id_str']}_{idx}")
  File "/nijigasaki-bot/nijigasaki/app/twitter.py", line 94, in fetch_and_push_img
    'twitter', f"[CQ:image,file=base64://{base64.b64encode(resp).decode('ascii')}]")
  File "/nijigasaki-bot/nijigasaki/model/subject.py", line 115, in push_update
    await get_bot().send_msg(**ctx, message=content)
  File "/usr/local/lib/python3.6/site-packages/aiocqhttp/api.py", line 184, in call_action
    raise ApiNotAvailable
aiocqhttp.exceptions.ApiNotAvailable
```

[message.txt](https://github.com/richardchien/python-aiocqhttp/files/3063706/message.txt)

**Comment by rikakomoe** [comment]
@rikakomoe 话说我突然觉得开个http server然后让酷Q过来拿似乎比base64清真

**Comment by nu1ee** [comment]
```
Task exception was never retrieved
future: <Task finished coro=<CQHttp._handle_event_payload_with_response() done, defined at C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\aiocqhttp\__init__.py:215> exception=ActionFailed()>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\aiocqhttp\__init__.py", line 217, in _handle_event_payload_with_response
    response = await self._handle_event_payload(payload)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\aiocqhttp\__init__.py", line 211, in _handle_event_payload
    await self._bus.emit(event, context)))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\aiocqhttp\bus.py", line 31, in emit
    results += await asyncio.gather(*coros)
  File "C:\Users\Administrator\Desktop\nuapp\bqqbot.py", line 52, in handle_msg
    await bot.send(ctx,'%s' % clipdata)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\aiocqhttp\__init__.py", line 256, in send
    return await self.send_msg(**context)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\aiocqhttp\api.py", line 170, in call_action
    action, **params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\aiocqhttp\api.py", line 140, in call_action
    return _handle_api_result(await ResultStore.fetch(seq))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\aiocqhttp\api.py", line 39, in _handle_api_result
    raise ActionFailed(retcode=result.get('retcode'))
aiocqhttp.exceptions.ActionFailed
```

```
os.system(r"%s\autot5key.exe %s"%(sys.path[0],ctx['message']))
pyperclip.copy("")
clipdata=pyperclip.paste()
if clipdata == "zcmerror":
	await bot.send(ctx, '注册码获取错误！ 请关闭WIFI共享和USB类连接(如手机,4G路由USB模式),后关闭5重新运行')
else:
	await bot.send(ctx,'%s' % clipdata)
```

**Comment by stdrc** [comment]
测试了一下，似乎没毛病，可能当时连接有问题吧
