### ISSUE TITLE
您的主机中的软件中止了一 个已建立的连接

### ISSUE THREAD

**Issue by jiangjiangflies** [cqmoe/python-aiocqhttp#41]
有时候处理消息会出现自动中断，log如下：

future: <Task finished name='Task-68' coro=<worker_serve.<locals>._server_callba
ck() done, defined at C:\Program Files\Python38\lib\site-packages\hypercorn\asyn
cio\run.py:88> exception=ConnectionAbortedError(10053, '您的主机中的软件中止了一
个已建立的连接。', None, 10053, None)>
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\site-packages\hypercorn\asyncio\run.py", l
ine 89, in _server_callback
    await TCPServer(app, loop, config, reader, writer)
  File "C:\Program Files\Python38\lib\site-packages\hypercorn\asyncio\tcp_server
.py", line 83, in run
    await self._close()
  File "C:\Program Files\Python38\lib\site-packages\hypercorn\asyncio\tcp_server
.py", line 129, in _close
    await self.writer.wait_closed()
  File "C:\Program Files\Python38\lib\asyncio\streams.py", line 359, in wait_clo
sed
    await self._protocol._get_close_waiter(self)
  File "C:\Program Files\Python38\lib\asyncio\proactor_events.py", line 395, in
_loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
  File "C:\Program Files\Python38\lib\asyncio\windows_events.py", line 528, in s
end
    ov.WSASend(conn.fileno(), buf, flags)
ConnectionAbortedError: [WinError 10053] 您的主机中的软件中止了一个已建立的连接
。

这是怎么回事？是不是处理消息用的时间过长？这是aiocqhttp的问题还是cqhttp-mirai插件的问题呢？脑壳疼。。。

**Comment by cleoold** [comment]
Were you using Python 3.8.0?
