### ISSUE TITLE
ImportError: cannot import name 'TypedDict' from 'typing_extensions'

### ISSUE THREAD

**Issue by User670** [cqmoe/python-aiocqhttp#52]
**问题描述**
在pip上更新了 nonebot ( [nonebot/nonebot](https://github.com/nonebot/nonebot) )（`pip install --upgrade nonebot`），更新过程中同时将aiocqhttp更新到了版本1.4.0，Quart更新到了0.14.1，hypercorn更新到了版本0.11.2。然后试图运行nonebot，在import nonebot处报错。试图在python的互动式界面中输入`import nonebot` 或 `import aiocqhttp`报相同的错误。见下面贴的报错信息。

**复现方法**
见上。

**期望的行为**
正常import相关库而不报错？

**日志信息**
```
Traceback (most recent call last):
File "C:\Program Files\Python37\lib\site-packages\hypercorn\typing.py", line 9, in <module>
    from typing import Literal, Protocol, TypedDict
ImportError: cannot import name 'Literal' from 'typing' (C:\Program Files\Python37\lib\typing.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bot.py", line 3, in <module>
    import nonebot
  File "C:\Program Files\Python37\lib\site-packages\nonebot\__init__.py", line 5, in <module>
    import aiocqhttp
  File "C:\Program Files\Python37\lib\site-packages\aiocqhttp\__init__.py", line 19, in <module>
    from quart import Quart, request, abort, jsonify, websocket, Response
  File "C:\Program Files\Python37\lib\site-packages\quart\__init__.py", line 6, in <module>
    from .app import Quart
  File "C:\Program Files\Python37\lib\site-packages\quart\app.py", line 32, in <module>
    from hypercorn.asyncio import serve
  File "C:\Program Files\Python37\lib\site-packages\hypercorn\asyncio\__init__.py", line 4, in <module>
    from .run import worker_serve
  File "C:\Program Files\Python37\lib\site-packages\hypercorn\asyncio\run.py", line 11, in <module>
    from .lifespan import Lifespan
  File "C:\Program Files\Python37\lib\site-packages\hypercorn\asyncio\lifespan.py", line 4, in <module>
    from ..typing import ASGIFramework, ASGIReceiveEvent, ASGISendEvent, LifespanScope
  File "C:\Program Files\Python37\lib\site-packages\hypercorn\typing.py", line 11, in <module>
    from typing_extensions import Literal, Protocol, TypedDict  # type: ignore
ImportError: cannot import name 'TypedDict' from 'typing_extensions' (C:\Program Files\Python37\lib\site-packages\typing_extensions.py)
```

**相关代码**
无

**运行环境**
 - 操作系统：Windows server 2012 R2, x64
 - OneBot（CQHTTP）实现及版本：无关
 - aiocqhttp 版本：1.4.0
 - Python 版本：3.7.3

**Comment by cleoold** [comment]
Hypercorn 的問題，依賴沒有安裝全.

解決辦法 1：使用 Python 3.8

解決辦法 2: `pip install typing_extensions`

**Comment by User670** [comment]
> Hypercorn 的問題，依賴沒有安裝全. 解決辦法 1：使用 Python 3.8 解決辦法 2: `pip install typing_extensions`

`pip install typing_extensions` -> "requirements already satisfied"

**Comment by cleoold** [comment]
確保你的 typing_extensions 是最新版的 （3.10.0.0 ）

**Comment by User670** [comment]
> 確保你的 typing_extensions 是最新版的 （3.10.0.0 ）

谢谢，之前装的版本貌似不是最新（3.7）。问题已解决

**Comment by cleoold** [comment]
I have submitted this bug to hypercorn. They might update this in the
future.

https://gitlab.com/pgjones/hypercorn/-/merge_requests/54
